### ISSUE TITLE
rotated glyphs not rendered correctly in preview window

### ISSUE THREAD

**Issue by pauldhunt** [adobe-type-tools/robofont-extensions#1]
If I have a glyph with a component with a transformation applied to rotate the component (something similar to: -1.0, 0, 0, -1.0, 580, 478), the shifting is applied in the preview window (580, 478), but the rotation is not (-1.0, 0, 0, -1.0).
![screen shot 2015-03-05 at 4 15 10 pm](https://cloud.githubusercontent.com/assets/2119748/6517657/44c7cfb4-c352-11e4-94f1-74beddd7881e.png)

**Comment by miguelsousa** [comment]
I've identified the problem and I'm trying to find the best way to fix it.

**Comment by miguelsousa** [comment]
Version 0.9.3 should fix this. Reopen in case it doesn't.
