### ISSUE TITLE
Slowness in RF3

### ISSUE THREAD

**Issue by rbmntjs** [adobe-type-tools/robofont-extensions#11]
The extension becomes incredibly slow after adding anchors to a relatively basic set of glyphs (UC, lc, 20-odd combining diacritics). Would be great to make this smoother.

**Comment by miguelsousa** [comment]
Source Sans has [almost 700 anchors on accent and base glyphs](https://github.com/adobe-fonts/source-sans-pro/blob/master/Roman/Masters/master_0/anchors) and I don't experience any significant slow down when adjusting those. There's only a minor lag, but that's to be expected since it's Python after all.

**Comment by rbmntjs** [comment]
This is with the preview open? I’m looking at major lag – over half a second for each single nudge to propagate to the preview, and also for it to show in the glyph window. This is on a MacBook Pro that is less than three months old, latest OS, RF 3.2. Any ideas on where to look for a fix?

**Comment by miguelsousa** [comment]
I'm using the window layout below. I've tested with RoboFont 1.8.4 running on a MacBook Pro 2016 with macOS 10.14.2. Haven't checked with RF 3.x.

<img width="1444" alt="screen shot 2019-02-04 at 12 28 23" src="https://user-images.githubusercontent.com/2119742/52235312-960afd80-2878-11e9-9919-c84553396109.png">

**Comment by miguelsousa** [comment]
~~When I try using the extension with the latest RF beta I get these tracebacks #12~~

**Comment by miguelsousa** [comment]
Tested Adjust Anchors v1.6.1 with RF3.3b and the lag when editing Source Sans' anchors is comparable to RF1.8.4.

**Comment by miguelsousa** [comment]
Got [another report of slowness in RF3](https://www.dropbox.com/s/ob6dhwbimxawsu2/AdjustAnchors.mov?dl=0). Have no idea on how to debug this, so #helpwanted

**Comment by miguelsousa** [comment]
@typemytype any pointers on how to speed things up?

**Comment by frankrolf** [comment]
FWIW the performance seems to be back to normal in RF Version 3.4b (build 2004031700) (possibly also earlier versions)
