### ISSUE TITLE
The keyboard shortcut for Adjust Anchors hijacks a default text editing shortcut

### ISSUE THREAD

**Issue by rbmntjs** [adobe-type-tools/robofont-extensions#2]
Pressing Control-A, as I do a hundred times a day to jump to the beginning of the line, now pops up the Adjust Anchors window instead. I appreciate the thinking behind a shortcut for a useful extension, but perhaps it could be a little bit more complicated than a single Control + letter.

**Comment by miguelsousa** [comment]
Fixed in version `0.9.2`.
