### ISSUE TITLE
ImportError: cannot import name NSScrollElasticityNone

### ISSUE THREAD

**Issue by typoman** [adobe-type-tools/robofont-extensions#4]
Hello,

I'm running RF Version 1.6 (built 1410152315) and the last update on Adjust Anchors caused a glitch in the extension. This is the output:

File "AdjustAnchors.py", line 35, in <module>
ImportError: cannot import name NSScrollElasticityNone

Now the extension doesn't launch. I could reproduce the error on my colleagues machine.
Best,

Bahman

**Comment by miguelsousa** [comment]
@bahman3d Update to the latest version. I fixed that problem a few days ago.
