### ISSUE TITLE
Feature addition

### ISSUE THREAD

**Issue by FosterType** [adobe-type-tools/robofont-extensions#5]
Hey Miguel,

Further to my comment on twitter, I thought an additional feature would be helpful if you had the time to implement it. The request is to add in an intermediate glyph function as in the space centre, so one might view all diacritics between certain strings. This function would provide  the ability to add a single space in between each glyph also, some times when diacritics very close together I find it hard to judge their justification. Thank you providing such a crucial part of my workflow!

Best,
Dave

**Comment by miguelsousa** [comment]
@FosterType I've just pushed some changes (version 1.2.0) that allow increasing the glyphs' side bearings, and therefore the space between adjacent glyphs.
Being able to insert glyphs between the accented glyphs will come next.

**Comment by FosterType** [comment]
Hey Miguel,

Thanks for integrating the idea so quickly, this will be a big help.

Dave

**Comment by miguelsousa** [comment]
Insertion of extra glyphs is now supported. Enjoy!
<img width="1077" alt="extraglyphs" src="https://cloud.githubusercontent.com/assets/2119742/10714213/443e91bc-7aa0-11e5-93c2-910220bae0ed.png">

**Comment by FosterType** [comment]
Massively helpful addition mate cheers!
